" KerML syntax, generated by editors/nvim/tools/gensyntax from
" internal/core/lexer.Keywords() and lexer.ContextualWords(); do not edit by hand.
if exists('b:current_syntax')
  finish
endif

syn case match

syn keyword kermlDeclaration action allocation analysis assoc attribute behavior binding calc
syn keyword kermlDeclaration case class classifier comment concern connection connector constraint
syn keyword kermlDeclaration datatype dependency doc enum event expr feature flow
syn keyword kermlDeclaration function interaction interface item language metaclass metadata multiplicity
syn keyword kermlDeclaration occurrence part port predicate rendering rep requirement state
syn keyword kermlDeclaration step struct type verification view viewpoint
syn keyword kermlDeclaration def namespace package nextgroup=kermlDeclarationName skipwhite
syn keyword kermlControl accept after assert assign at decide do else
syn keyword kermlControl entry exhibit exit first for fork if include
syn keyword kermlControl join loop merge parallel perform render require return
syn keyword kermlControl satisfy send succession terminate then to transition until
syn keyword kermlControl via when while
syn keyword kermlModifier abstract all composite const constant default derived end
syn keyword kermlModifier in individual inout member new nonunique ordered out
syn keyword kermlModifier portion private protected public ref snapshot standard timeslice
syn keyword kermlModifier variant variation
syn keyword kermlModifier library nextgroup=kermlDeclarationName skipwhite
syn keyword kermlRelationship conjugate conjugates conjugation crosses differences disjoining disjoint featured
syn keyword kermlRelationship featuring import intersects inverse inverting redefines redefinition references
syn keyword kermlRelationship specialization specializes subclassifier subset subsets subtype typed typing
syn keyword kermlRelationship unions
syn keyword kermlRelationship alias nextgroup=kermlDeclarationName skipwhite
syn keyword kermlWordOperator and as chains defined hastype implies istype meta
syn keyword kermlWordOperator not or xor
syn keyword kermlConstant false null true
syn keyword kermlKeyword about actor allocate assume bind bool by connect
syn keyword kermlKeyword expose filter frame from inv locale message objective
syn keyword kermlKeyword of stakeholder subject use verify
syn keyword kermlContextual chain choice deep defer done history junction point
syn keyword kermlContextual shallow var

" Vim gives the last definition priority when items start at the same
" position (TextMate rule order is first-wins), so the general matches
" come first and comments, strings and quoted names come last.
syn match kermlNamespace /\<[A-Za-z_][A-Za-z0-9_]*\%(\s*::\)\@=/
syn match kermlNumber /\<\d\+\%(\.\d\+\)\?\%([eE][+-]\?\d\+\)\?\>/
syn match kermlOperator ,:>>\|::>\|:>\|=>\|->\|\.\.\|\*\*\|[=+\-*/<>!&|^~?@],
syn match kermlTypeOperator ,:>>\|::>\|:>\|:, nextgroup=kermlTypeReference skipwhite
syn match kermlTypeReference /\%([A-Za-z_][A-Za-z0-9_]*::\)*\%([A-Za-z_][A-Za-z0-9_]*\|'[^']*'\)/ contained
syn match kermlDeclarationName /\%([A-Za-z_][A-Za-z0-9_]*\|'[^']*'\)/ contained
syn match kermlEscape /\\./ contained
syn region kermlString start=/"/ skip=/\\./ end=/"/ contains=kermlEscape
syn region kermlQuotedName start=/'/ skip=/\\./ end=/'/ contains=kermlEscape
syn match kermlLineComment ,//.*$,
syn region kermlBlockComment start=,/\*, end=,\*/,

syn sync ccomment kermlBlockComment
syn sync minlines=200

hi def link kermlDeclaration Structure
hi def link kermlControl Statement
hi def link kermlModifier StorageClass
hi def link kermlRelationship Keyword
hi def link kermlWordOperator Operator
hi def link kermlConstant Constant
hi def link kermlKeyword Keyword
hi def link kermlContextual Statement
hi def link kermlNamespace Identifier
hi def link kermlNumber Number
hi def link kermlOperator Operator
hi def link kermlTypeOperator Operator
hi def link kermlTypeReference Type
hi def link kermlDeclarationName Type
hi def link kermlEscape SpecialChar
hi def link kermlString String
hi def link kermlQuotedName Identifier
hi def link kermlLineComment Comment
hi def link kermlBlockComment Comment

let b:current_syntax = 'kerml'
