" SysML v2 syntax, generated by editors/nvim/tools/gensyntax from
" internal/core/lexer.Keywords() and lexer.ContextualWords(); do not edit by hand.
if exists('b:current_syntax')
  finish
endif

syn case match

syn keyword sysmlDeclaration action allocation analysis assoc attribute behavior binding calc
syn keyword sysmlDeclaration case class classifier comment concern connection connector constraint
syn keyword sysmlDeclaration datatype dependency doc enum event expr feature flow
syn keyword sysmlDeclaration function interaction interface item language metaclass metadata multiplicity
syn keyword sysmlDeclaration occurrence part port predicate rendering rep requirement state
syn keyword sysmlDeclaration step struct type verification view viewpoint
syn keyword sysmlDeclaration def namespace package nextgroup=sysmlDeclarationName skipwhite
syn keyword sysmlControl accept after assert assign at decide do else
syn keyword sysmlControl entry exhibit exit first for fork if include
syn keyword sysmlControl join loop merge parallel perform render require return
syn keyword sysmlControl satisfy send succession terminate then to transition until
syn keyword sysmlControl via when while
syn keyword sysmlModifier abstract all composite const constant default derived end
syn keyword sysmlModifier in individual inout member new nonunique ordered out
syn keyword sysmlModifier portion private protected public ref snapshot standard timeslice
syn keyword sysmlModifier variant variation
syn keyword sysmlModifier library nextgroup=sysmlDeclarationName skipwhite
syn keyword sysmlRelationship conjugate conjugates conjugation crosses differences disjoining disjoint featured
syn keyword sysmlRelationship featuring import intersects inverse inverting redefines redefinition references
syn keyword sysmlRelationship specialization specializes subclassifier subset subsets subtype typed typing
syn keyword sysmlRelationship unions
syn keyword sysmlRelationship alias nextgroup=sysmlDeclarationName skipwhite
syn keyword sysmlWordOperator and as chains defined hastype implies istype meta
syn keyword sysmlWordOperator not or xor
syn keyword sysmlConstant false null true
syn keyword sysmlKeyword about actor allocate assume bind bool by connect
syn keyword sysmlKeyword expose filter frame from inv locale message objective
syn keyword sysmlKeyword of stakeholder subject use verify
syn keyword sysmlContextual chain choice deep defer done history junction point
syn keyword sysmlContextual shallow

" Vim gives the last definition priority when items start at the same
" position (TextMate rule order is first-wins), so the general matches
" come first and comments, strings and quoted names come last.
syn match sysmlNamespace /\<[A-Za-z_][A-Za-z0-9_]*\%(\s*::\)\@=/
syn match sysmlNumber /\<\d\+\%(\.\d\+\)\?\%([eE][+-]\?\d\+\)\?\>/
syn match sysmlOperator ,:>>\|::>\|:>\|=>\|->\|\.\.\|\*\*\|[=+\-*/<>!&|^~?@],
syn match sysmlTypeOperator ,:>>\|::>\|:>\|:, nextgroup=sysmlTypeReference skipwhite
syn match sysmlTypeReference /\%([A-Za-z_][A-Za-z0-9_]*::\)*\%([A-Za-z_][A-Za-z0-9_]*\|'[^']*'\)/ contained
syn match sysmlDeclarationName /\%([A-Za-z_][A-Za-z0-9_]*\|'[^']*'\)/ contained
syn match sysmlEscape /\\./ contained
syn region sysmlString start=/"/ skip=/\\./ end=/"/ contains=sysmlEscape
syn region sysmlQuotedName start=/'/ skip=/\\./ end=/'/ contains=sysmlEscape
syn match sysmlLineComment ,//.*$,
syn region sysmlBlockComment start=,/\*, end=,\*/,

syn sync ccomment sysmlBlockComment
syn sync minlines=200

hi def link sysmlDeclaration Structure
hi def link sysmlControl Statement
hi def link sysmlModifier StorageClass
hi def link sysmlRelationship Keyword
hi def link sysmlWordOperator Operator
hi def link sysmlConstant Constant
hi def link sysmlKeyword Keyword
hi def link sysmlContextual Statement
hi def link sysmlNamespace Identifier
hi def link sysmlNumber Number
hi def link sysmlOperator Operator
hi def link sysmlTypeOperator Operator
hi def link sysmlTypeReference Type
hi def link sysmlDeclarationName Type
hi def link sysmlEscape SpecialChar
hi def link sysmlString String
hi def link sysmlQuotedName Identifier
hi def link sysmlLineComment Comment
hi def link sysmlBlockComment Comment

let b:current_syntax = 'sysml'
