package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/Open-MBEE/OpenSysML/editors/internal/keywords"
	"github.com/Open-MBEE/OpenSysML/internal/core/lexer"
	"github.com/Open-MBEE/OpenSysML/internal/core/source"
)

// Syntax describes one generated Vim syntax file.
type Syntax struct {
	File     string // file name under syntax/
	Name     string // language name for the header comment
	Filetype string // filetype the file serves; also its group-name prefix
	Kind     source.Kind
}

// Syntaxes returns the syntax files shipped by the plugin. SysML v2 and KerML
// share a keyword set, so they share every rule but their group-name prefix and
// the contextual words their own grammar reads as syntax.
func Syntaxes() []Syntax {
	return []Syntax{
		{File: "sysml.vim", Name: "SysML v2", Filetype: "sysml", Kind: source.KindSysML},
		{File: "kerml.vim", Name: "KerML", Filetype: "kerml", Kind: source.KindKerML},
	}
}

// keywordHighlights maps a shared keyword group to its group-name suffix and
// default highlight link; a group the map misses fails generation.
var keywordHighlights = map[string]struct{ suffix, link string }{
	"declaration":  {"Declaration", "Structure"},
	"control":      {"Control", "Statement"},
	"modifier":     {"Modifier", "StorageClass"},
	"relationship": {"Relationship", "Keyword"},
	"operator":     {"WordOperator", "Operator"},
	"constant":     {"Constant", "Constant"},
}

const identifier = `[A-Za-z_][A-Za-z0-9_]*`

// declarators introduce a name (`part def Vehicle`); their keyword items
// chain to the DeclarationName match via nextgroup.
var declarators = map[string]bool{
	"def":       true,
	"package":   true,
	"namespace": true,
	"alias":     true,
	"library":   true,
}

// keywordsPerLine keeps `syn keyword` lines short enough that adding one
// keyword touches one line of the generated file.
const keywordsPerLine = 8

// Render returns the text of a syntax file, ending in a newline.
func Render(s Syntax) ([]byte, error) {
	groups, rest, err := keywords.Partition()
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	w := func(parts ...string) {
		buf.WriteString(strings.Join(parts, ""))
		buf.WriteByte('\n')
	}
	group := func(suffix string) string { return s.Filetype + suffix }

	type hilink struct{ group, link string }
	var links []hilink
	keyword := func(suffix, link string, kws []string) {
		var plain, declaring []string
		for _, kw := range kws {
			if declarators[kw] {
				declaring = append(declaring, kw)
			} else {
				plain = append(plain, kw)
			}
		}
		sort.Strings(plain)
		sort.Strings(declaring)
		for start := 0; start < len(plain); start += keywordsPerLine {
			end := min(start+keywordsPerLine, len(plain))
			w(`syn keyword `, group(suffix), ` `, strings.Join(plain[start:end], " "))
		}
		if len(declaring) > 0 {
			w(`syn keyword `, group(suffix), ` `, strings.Join(declaring, " "),
				` nextgroup=`, group("DeclarationName"), ` skipwhite`)
		}
		links = append(links, hilink{group(suffix), link})
	}
	match := func(suffix, link, rule string) {
		w(`syn match `, group(suffix), ` `, rule)
		links = append(links, hilink{group(suffix), link})
	}
	region := func(suffix, link, rule string) {
		w(`syn region `, group(suffix), ` `, rule)
		links = append(links, hilink{group(suffix), link})
	}

	w(`" `, s.Name, ` syntax, generated by editors/nvim/tools/gensyntax from`)
	w(`" internal/core/lexer.Keywords() and lexer.ContextualWords(); do not edit by hand.`)
	w(`if exists('b:current_syntax')`)
	w(`  finish`)
	w(`endif`)
	w(``)
	w(`syn case match`)
	w(``)

	for _, g := range groups {
		target, ok := keywordHighlights[g.Name]
		if !ok {
			return nil, fmt.Errorf("keyword group %q has no highlight group", g.Name)
		}
		keyword(target.suffix, target.link, g.Keywords)
	}
	// Anything the lexer knows and no group claims still highlights as a
	// keyword, so a new keyword needs no syntax change.
	if len(rest) > 0 {
		keyword("Keyword", "Keyword", rest)
	}
	// The words the parser reads as syntax positionally (`initial`, `done`)
	// without the lexer reserving them.
	if contextual := lexer.ContextualWords(s.Kind); len(contextual) > 0 {
		keyword("Contextual", "Statement", contextual)
	}

	w(``)
	w(`" Vim gives the last definition priority when items start at the same`)
	w(`" position (TextMate rule order is first-wins), so the general matches`)
	w(`" come first and comments, strings and quoted names come last.`)
	// A namespace segment of a qualified name, e.g. `ScalarValues::Real`.
	match("Namespace", "Identifier", `/\<`+identifier+`\%(\s*::\)\@=/`)
	match("Number", "Number", `/\<\d\+\%(\.\d\+\)\?\%([eE][+-]\?\d\+\)\?\>/`)
	match("Operator", "Operator", `,:>>\|::>\|:>\|=>\|->\|\.\.\|\*\*\|[=+\-*/<>!&|^~?@],`)
	// The type a feature is typed by or specializes; the operator chains to
	// the name via nextgroup.
	match("TypeOperator", "Operator", `,:>>\|::>\|:>\|:, nextgroup=`+group("TypeReference")+` skipwhite`)
	match("TypeReference", "Type", `/\%(`+identifier+`::\)*\%(`+identifier+`\|'[^']*'\)/ contained`)
	// The name a declaration introduces, e.g. `part def Vehicle`.
	match("DeclarationName", "Type", `/\%(`+identifier+`\|'[^']*'\)/ contained`)
	match("Escape", "SpecialChar", `/\\./ contained`)
	region("String", "String", `start=/"/ skip=/\\./ end=/"/ contains=`+group("Escape"))
	// A quoted name, e.g. `part 'left wheel';`.
	region("QuotedName", "Identifier", `start=/'/ skip=/\\./ end=/'/ contains=`+group("Escape"))
	match("LineComment", "Comment", `,//.*$,`)
	region("BlockComment", "Comment", `start=,/\*, end=,\*/,`)

	w(``)
	w(`syn sync ccomment `, group("BlockComment"))
	w(`syn sync minlines=200`)
	w(``)
	for _, l := range links {
		w(`hi def link `, l.group, ` `, l.link)
	}
	w(``)
	w(`let b:current_syntax = '`, s.Filetype, `'`)

	return buf.Bytes(), nil
}
